### ISSUE TITLE
Log in / Sign up flow and fancy inputs

### ISSUE THREAD

**Issue by kimberlym4488** [kelseybrianne/will-it-fit#26]

**Comment by jmichaelbrown8** [comment]
Still to do:

- [ ] Error messaging to let the user know how to address issues
- [ ] TextField adornments to tell them which unit to supply
- [ ] Top right header menu swap to user's profile avatar with a menu to:
    - [ ] View/Edit Own Closet
    - [ ] View/Edit Own Saved Items
    - [ ] Edit Profile/Measurements
    - [ ] Log Out
